### ISSUE TITLE
执行路径名中存在空格如何处理，单引号转义无效

### ISSUE THREAD

**Issue by Tback1** [hezhizheng/go-crontab#2]
例如这样的路径  "node d:\\'4 Node'\\4\\test.js"

.--------.---------------.------------------------------.----------.
| 任务ID |    表达式     |           执行命令           | 错误信息 |
+--------+---------------+------------------------------+----------+
|      1 | 0/5 * * * * ? | node d:\'4 Node'\4\test.js |   nil    |
'--------'---------------'------------------------------'----------'
输入任意键退出

{"level":"info","msg":"执行命令： node d:\\'4 Node'\\4\\test.js 输出： node:internal/modules/cjs/loader:930\r\n  throw err;\r\n

实际识别成了d:\4的路径，对空格没有很好地处理

试过
`"node d:\'4 Node'\4\test.js"`
`"node d:\4 Node\4\test.js"`
`"node d:\\"4 Node"\\4\\test.js"`
路径转义始终失败

**Comment by hezhizheng** [comment]
> 例如这样的路径 "node d:\'4 Node'\4\test.js"
> 
> .--------.---------------.------------------------------.----------. | 任务ID | 表达式 | 执行命令 | 错误信息 | +--------+---------------+------------------------------+----------+ | 1 | 0/5 * * * * ? | node d:'4 Node'\4\test.js | nil | '--------'---------------'------------------------------'----------' 输入任意键退出
> 
> {"level":"info","msg":"执行命令： node d:\'4 Node'\4\test.js 输出： node:internal/modules/cjs/loader:930\r\n throw err;\r\n
> 
> 实际识别成了d:\4的路径，对空格没有很好地处理
> 
> 试过 `"node d:\'4 Node'\4\test.js"` `"node d:\4 Node\4\test.js"` `"node d:\\"4 Node"\\4\\test.js"` 路径转义始终失败

建议尽量贴上 config.json 的配置文件
此问题可以尝试先进入 `d:\4 Node\4`  这个目录再执行  `node test.js` 命令
即在配置文件设置 cmd 为 "d: && cd d:\\4 Node\\4 && node test.js" 
```
cmd 环境
{
   "app": {
    "model": "s",
    "exec_mode":"",
    "crontab_cmd": [
      {
        "crontab": "0 0/1 * * * ?",
        "cmd": "d: && cd d:\\4 Node\\4 && node test.js"
      }
    ]
  }
}
```

```
bash 环境
{
    "app": {
        "model": "s",
        "exec_mode": "bash",
        "crontab_cmd": [
            {
                "crontab": "0 0/1 * * * ?",
                "cmd": "cd /d/4\\ Node/4/ && node test.js"
            }
        ]
    }
}
```
@Tback1

**Comment by Tback1** [comment]
@hezhizheng  谢谢，已经这个思路可以解决。我采用的是另一个思路，直接改名`4 node` 为`4_node` 但是迟早会遇到无法改名绕过的。还是得采取先进入目录的思路
