### ISSUE TITLE
启动终端一退出，定时任务就用不了了

### ISSUE THREAD

**Issue by zhonglunsheng** [hezhizheng/go-crontab#4]

**Comment by hezhizheng** [comment]
需要保持终端的开启才能保证程序的运行，Windows下如需常驻可以考虑使用 [winsw](https://github.com/winsw/winsw) 将 go-crontab 打包成一个Windows服务。 @zhonglunsheng

**Comment by Goojoe** [comment]
给个我的winsw配置,运行winsw-mg.bat管理服务即可
[go-crontab-win64.zip](https://github.com/hezhizheng/go-crontab/files/11769533/go-crontab-win64.zip)
