### ISSUE TITLE
windows日志输出，表达式和执行命令显示反了

### ISSUE THREAD

**Issue by maoxuner** [hezhizheng/go-crontab#5]
![image](https://github.com/user-attachments/assets/9c8e93c5-70c6-487b-a654-2c4f72a86358)

**Comment by hezhizheng** [comment]
已处理  可以使用最新版   https://github.com/hezhizheng/go-crontab/releases/tag/v0.1.0

**Comment by maoxuner** [comment]
![image](https://github.com/user-attachments/assets/fe6f5ff6-d4e0-4f9c-8d68-1df3691dcb8e)
![image](https://github.com/user-attachments/assets/077f9c5e-dee1-40c5-8961-aa3211aef1ac)

这个版本总是被浏览器拦截，说是有病毒 :(

**Comment by hezhizheng** [comment]
> ![image](https://private-user-images.githubusercontent.com/104855611/391770087-fe6f5ff6-d4e0-4f9c-8d68-1df3691dcb8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxOTE1ODMsIm5iZiI6MTczMzE5MTI4MywicGF0aCI6Ii8xMDQ4NTU2MTEvMzkxNzcwMDg3LWZlNmY1ZmY2LWQ0ZTAtNGY5Yy04ZDY4LTFkZjM2OTFkY2I4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwMjAxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWVmYjM1MDk1YTM5OWUwZTBmMTAzZTUzNjlmYjA0MmIxNmMwYTQwNDMxOWIwMTNjODM3MGQ4ZjIzMjRkZGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YlcIyQGWPpJN5we2HL4t5vdJ6CJkbY5W_P1ZVJGTLnA) ![image](https://private-user-images.githubusercontent.com/104855611/391774650-077f9c5e-dee1-40c5-8961-aa3211aef1ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxOTE1ODMsIm5iZiI6MTczMzE5MTI4MywicGF0aCI6Ii8xMDQ4NTU2MTEvMzkxNzc0NjUwLTA3N2Y5YzVlLWRlZTEtNDBjNS04OTYxLWFhMzIxMWFlZjFhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwMjAxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDM3NTQ5MzQzMjA4ODdhNmUwMDY1MzAwMTIyMTQ2YjYwZjdjMGI1YTE4Zjk1ZTZmNWNmZTlmZjU5NGU3MTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.89IDjZNDGjYqwvjSXT_BUYf0EfZU0SNp9aiktPYmTJ4)
> 
> 这个版本总是被浏览器拦截，说是有病毒 :(

都是一样的编译方式  换个浏览器  或者把Windows 防火墙 关闭了 试试

**Comment by maoxuner** [comment]
> > ![image](https://private-user-images.githubusercontent.com/104855611/391770087-fe6f5ff6-d4e0-4f9c-8d68-1df3691dcb8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxOTE1ODMsIm5iZiI6MTczMzE5MTI4MywicGF0aCI6Ii8xMDQ4NTU2MTEvMzkxNzcwMDg3LWZlNmY1ZmY2LWQ0ZTAtNGY5Yy04ZDY4LTFkZjM2OTFkY2I4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwMjAxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWVmYjM1MDk1YTM5OWUwZTBmMTAzZTUzNjlmYjA0MmIxNmMwYTQwNDMxOWIwMTNjODM3MGQ4ZjIzMjRkZGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YlcIyQGWPpJN5we2HL4t5vdJ6CJkbY5W_P1ZVJGTLnA) ![image](https://private-user-images.githubusercontent.com/104855611/391774650-077f9c5e-dee1-40c5-8961-aa3211aef1ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxOTE1ODMsIm5iZiI6MTczMzE5MTI4MywicGF0aCI6Ii8xMDQ4NTU2MTEvMzkxNzc0NjUwLTA3N2Y5YzVlLWRlZTEtNDBjNS04OTYxLWFhMzIxMWFlZjFhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwMjAxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDM3NTQ5MzQzMjA4ODdhNmUwMDY1MzAwMTIyMTQ2YjYwZjdjMGI1YTE4Zjk1ZTZmNWNmZTlmZjU5NGU3MTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.89IDjZNDGjYqwvjSXT_BUYf0EfZU0SNp9aiktPYmTJ4)
> > 这个版本总是被浏览器拦截，说是有病毒 :(
> 
> 都是一样的编译方式 换个浏览器 或者把Windows 防火墙 关闭了 试试

只能先给它加白名单了。感谢您开发这个工具，帮大忙了
